require: 
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - vendor/**/*.rb
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Rails/I18nLocaleTexts:
  Enabled: false
